DoAnTotNghiep_New/DoAnTotNghiep/DoAn_NguyenVanTruong/Models/Product_Size.cs
namespace DoAnNguyenVanTruong.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Product_Size
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Size()
        {
            CartItems = new HashSet<CartItem>();
            OrderDetails = new HashSet<OrderDetail>();
        }

        public int Product_SizeID { get; set; }

        public int? ProductID { get; set; }

        public int? SizeID { get; set; }

        public int? Quantity { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItems { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }

        public virtual Product Product { get; set; }

        public virtual Size Size { get; set; }
    }
}

DoAnTotNghiep_New/DoAnTotNghiep/DoAn_NguyenVanTruong/Controllers/Product_SizeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAnNguyenVanTruong.Models;
using PagedList;

namespace DoAnNguyenVanTruong.Controllers
{
    public class Product_SizeController : Controller
    {
        private BaseAppDbContext db = new BaseAppDbContext();

        // GET: Product_Size
        public ActionResult Index(int? page, int? PageSize)
        {
            if (page == null)
            {
                page = 1;
            }
            if (PageSize == null)
            {

                PageSize = 8;
            }
            var product_sizes = db.Product_Size.ToList();
            return View(product_sizes.ToPagedList((int)page, (int)PageSize));
        }


        // GET: Product_Size/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product_Size product_Size = db.Product_Size.Find(id);
            if (product_Size == null)
            {
                return HttpNotFound();
            }
            return View(product_Size);
        }

        // GET: Product_Size/Create
        public ActionResult Create()
        {
            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "ProductName");
            ViewBag.SizeID = new SelectList(db.Sizes, "SizeID", "NameSize");
            return View();
        }

        // POST: Product_Size/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Product_SizeID,ProductID,SizeID,Quantity")] Product_Size product_Size)
        {
            if (ModelState.IsValid)
            {
                Product_Size pro_Size = db.Product_Size.FirstOrDefault(s=>s.ProductID==product_Size.ProductID && s.SizeID==product_Size.SizeID);
                if(pro_Size == null)
                {
                    db.Product_Size.Add(product_Size);
                }
                else if(pro_Size!=null)
                {
                    pro_Size.Quantity += product_Size.Quantity;
                    db.Product_Size.Attach(pro_Size);
                    db.Entry(pro_Size).State = EntityState.Modified;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "ProductName", product_Size.ProductID);
            ViewBag.SizeID = new SelectList(db.Sizes, "SizeID", "NameSize", product_Size.SizeID);
            return View(product_Size);
        }

        // GET: Product_Size/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product_Size product_Size = db.Product_Size.Find(id);
            if (product_Size == null)
            {
                return HttpNotFound();
            }
            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "ProductName", product_Size.ProductID);
            ViewBag.SizeID = new SelectList(db.Sizes, "SizeID", "NameSize", product_Size.SizeID);
            return View(product_Size);
        }

        // POST: Product_Size/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Product_SizeID,ProductID,SizeID,Quantity")] Product_Size product_Size)
        {
            if (ModelState.IsValid)
            {
                var productchangeList = db.Product_Size
                    .Where(x => x.ProductID == product_Size.ProductID)
                    .ToList();

                if (productchangeList.Any())
                {
                    var productchange = productchangeList.First();
                    productchange.SizeID = 1;
                    product_Size.SizeID = product_Size.SizeID;
                    productchange.Quantity = product_Size.Quantity;

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ModelState.AddModelError("", "Không tìm thấy sản phẩm để cập nhật.");
            }

            ViewBag.ProductID = new SelectList(db.Products, "ProductID", "ProductName", product_Size.ProductID);
            ViewBag.SizeID = new SelectList(db.Sizes, "SizeID", "NameSize", product_Size.SizeID);
            return View(product_Size);
        }


        // GET: Product_Size/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product_Size product_Size = db.Product_Size.Find(id);
            if (product_Size == null)
            {
                return HttpNotFound();
            }
            return View(product_Size);
        }

        // POST: Product_Size/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product_Size product_Size = db.Product_Size.Find(id);
            db.Product_Size.Remove(product_Size);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAnTotNghiep_New/DoAnTotNghiep/DoAn_NguyenVanTruong/Views/Product_Size/Create.cshtml
@model DoAnNguyenVanTruong.Models.Product_Size

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}
<div class="main-content-inner">
    <!-- main-content-wrap -->
    <div class="main-content-wrap">
        <div class="flex items-center flex-wrap justify-between gap20 mb-27">
            <h3>Nhập kho</h3>
            <ul class="breadcrumbs flex items-center flex-wrap justify-start gap10">
                <li>
                    <a href="/Admin/Dashboard"><div class="text-tiny">Trang chủ</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <a href="#"><div class="text-tiny">Quản lý</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <div class="text-tiny">Quản lý kho</div>
                </li>
            </ul>
        </div>
        <!-- new-attribute -->
        <div class="wg-box">
            <form action="/Product_Size/Create" method="post" class="form-new-product form-style-1">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <fieldset class="name">
                    <div class="body-title">Sản phẩm</div>
                    @Html.DropDownList("ProductID", null, htmlAttributes: new { @class = "flex-grow" })
                    @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "flex-grow" })
                </fieldset>
                @*<fieldset class="name">
                    <div class="body-title">Size</div>
                    @Html.DropDownList("SizeID", null, htmlAttributes: new { @class = "flex-grow" })
                    @Html.ValidationMessageFor(model => model.SizeID, "", new { @class = "flex-grow" })
                </fieldset>*@
                <fieldset class="name">
                    <div class="body-title">Số lượng trong kho</div>
                    <input class="flex-grow" type="text" placeholder="Số lượng trong kho" name="Quantity" tabindex="0" value="" aria-required="true" required="">
                </fieldset>
                <div class="bot">
                    <div></div>
                    <button class="tf-button w208" type="submit">Thêm mới</button>
                </div>
            </form>
        </div>
        <!-- /new-category -->
    </div>
    <!-- /main-content-wrap -->
</div>
<div class="bottom-page">
    <div class="body-text">Copyright © 2024 Mobile</div>
    <i class="icon-heart"></i>
</div>

DoAnTotNghiep_New/DoAnTotNghiep/DoAn_NguyenVanTruong/Views/Product_Size/Delete.cshtml
@model DoAnNguyenVanTruong.Models.Product_Size

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}
<div class="main-content-inner">
    <!-- main-content-wrap -->
    <div class="main-content-wrap">
        <div class="flex items-center flex-wrap justify-between gap20 mb-27">
            <h3>Xoá sản phẩm trong kho</h3>
            <ul class="breadcrumbs flex items-center flex-wrap justify-start gap10">
                <li>
                    <a href="/Admin/Dashboard"><div class="text-tiny">Trang chủ</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <a href="#"><div class="text-tiny">Quản lý</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <div class="text-tiny">Quản lý kho</div>
                </li>
            </ul>
        </div>
        <!-- new-attribute -->
        <div class="wg-box">
            <form action="/Product_Size/Delete/@Model.ProductID" method="post" class="form-new-product form-style-1">
                @Html.AntiForgeryToken()
                <fieldset class="name">
                    <div class="body-title">sản phẩm</div>
                    <input class="flex-grow" type="text" placeholder="Size" name="Quantity" tabindex="0" value="@Model.Product.ProductName" aria-required="true" required="" readonly>
                </fieldset>
                @*<fieldset class="name">
                    <div class="body-title">Size</div>
                    <input class="flex-grow" type="text" placeholder="Size" name="Quantity" tabindex="0" value="@Model.Size.NameSize" aria-required="true" required="" readonly>
                </fieldset>*@
                <fieldset class="name">
                    <div class="body-title">Số lượng trong kho</div>
                    <input class="flex-grow" type="text" placeholder="Số lượng trong kho" name="Quantity" tabindex="0" value="@Model.Quantity" aria-required="true" required="" readonly>
                </fieldset>
                <div class="bot">
                    <div></div>
                    <button class="tf-button w208" type="submit">Xoá</button>
                </div>
            </form>
        </div>
        <!-- /new-category -->
    </div>
    <!-- /main-content-wrap -->
</div>
<div class="bottom-page">
    <div class="body-text">Copyright © 2024 Mobile</div>
    <i class="icon-heart"></i>
</div>

DoAnTotNghiep_New/DoAnTotNghiep/DoAn_NguyenVanTruong/Views/Product_Size/Details.cshtml
@model DoAnNguyenVanTruong.Models.Product_Size

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}
<div class="main-content-inner">
    <!-- main-content-wrap -->
    <div class="main-content-wrap">
        <div class="flex items-center flex-wrap justify-between gap20 mb-27">
            <h3>Chi tiết sản phẩm trong kho</h3>
            <ul class="breadcrumbs flex items-center flex-wrap justify-start gap10">
                <li>
                    <a href="/Admin/Dashboard"><div class="text-tiny">Trang chủ</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <a href="#"><div class="text-tiny">Quản lý</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <div class="text-tiny">Quản lý kho</div>
                </li>
            </ul>
        </div>
        <!-- new-attribute -->
        <div class="wg-box">
            <form class="form-new-product form-style-1">

                <fieldset class="name">
                    <div class="body-title">sản phẩm</div>
                    <input class="flex-grow" type="text" placeholder="Size" name="ProductID" tabindex="0" value="@Model.Product.ProductName" aria-required="true" required="" readonly>
                </fieldset>
                @*<fieldset class="name">
                    <div class="body-title">Size</div>
                    <input class="flex-grow" type="text" placeholder="Size" name="SizeID" tabindex="0" value="@Model.Size.NameSize" aria-required="true" required="" readonly>
                </fieldset>*@
                <fieldset class="name">
                    <div class="body-title">Số lượng trong kho</div>
                    <input class="flex-grow" type="text" placeholder="Số lượng trong kho" name="Quantity" tabindex="0" value="@Model.Quantity" aria-required="true" required="" readonly>
                </fieldset>
                <div class="bot">
                    <div></div>
                    <a class="tf-button w208" href="/Product_Size/Edit/@Model.ProductID">Sửa</a>
                </div>
            </form>
        </div>
        <!-- /new-category -->
    </div>
    <!-- /main-content-wrap -->
</div>
<div class="bottom-page">
    <div class="body-text">Copyright © 2024 Mobile</div>
    <i class="icon-heart"></i>
</div>

DoAnTotNghiep_New/DoAnTotNghiep/DoAn_NguyenVanTruong/Views/Product_Size/Edit.cshtml
@model DoAnNguyenVanTruong.Models.Product_Size

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}

<div class="main-content-inner">
    <!-- main-content-wrap -->
    <div class="main-content-wrap">
        <div class="flex items-center flex-wrap justify-between gap20 mb-27">
            <h3>Sửa thông tin kho</h3>
            <ul class="breadcrumbs flex items-center flex-wrap justify-start gap10">
                <li>
                    <a href="/Admin/Dashboard"><div class="text-tiny">Trang chủ</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <a href="#"><div class="text-tiny">Quản lý</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <div class="text-tiny">Quản lý kho</div>
                </li>
            </ul>
        </div>
        <!-- new-attribute -->
        <div class="wg-box">
            <form action="/Product_Size/Edit" method="post" class="form-new-product form-style-1">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.ProductID)
                <fieldset class="name">
                    <div class="body-title">sản phẩm</div>
                    <input class="flex-grow" type="text" placeholder="Size" name="ProductID" tabindex="0" value="@Model.Product.ProductName" aria-required="true" required="" readonly>
                </fieldset>
                @*<fieldset class="name">
                    <div class="body-title">Size</div>
                    <input class="flex-grow" type="text" placeholder="Size" name="SizeID" tabindex="0" value="@Model.Size.NameSize" aria-required="true" required="" readonly>
                </fieldset>*@
                <fieldset class="name">
                    <div class="body-title">Số lượng trong kho</div>
                    <input class="flex-grow" type="text" placeholder="Số lượng trong kho" name="Quantity" tabindex="0" value="@Model.Quantity" aria-required="true" required="">
                </fieldset>
                <div class="bot">
                    <div></div>
                    <button class="tf-button w208" >Lưu</button>
                </div>
            </form>
        </div>
        <!-- /new-category -->
    </div>
    <!-- /main-content-wrap -->
</div>
<div class="bottom-page">
    <div class="body-text">Copyright © 2024 Mobile</div>
    <i class="icon-heart"></i>
</div>

DoAnTotNghiep_New/DoAnTotNghiep/DoAn_NguyenVanTruong/Views/Product_Size/Index.cshtml
@using PagedList.Mvc;
@using PagedList;
@model IPagedList<DoAnNguyenVanTruong.Models.Product_Size>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}
<div class="main-content-inner">
    <!-- main-content-wrap -->
    <div class="main-content-wrap">
        <div class="flex items-center flex-wrap justify-between gap20 mb-27">
            <h3>Danh sách sản phẩm trong kho</h3>
            <ul class="breadcrumbs flex items-center flex-wrap justify-start gap10">
                <li>
                    <a href="/Admin/Dashboard"><div class="text-tiny">Trang chủ</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <a href="#"><div class="text-tiny">Quản lý</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <div class="text-tiny">Quản lý kho</div>
                </li>
            </ul>
        </div>
        <!-- all-attribute -->
        <div class="wg-box">
            <div class="flex items-center justify-between gap10 flex-wrap">

                <a class="tf-button style-1 w208" href="/Product_Size/Create"><i class="icon-plus"></i>Thêm mới</a>
            </div>
            <div class="wg-table table-all-attribute">
                <ul class="table-title flex gap20 mb-14">
                    <li>
                        <div class="body-title">Sản phẩm</div>
                    </li>
                    <li>
                        <div class="body-title" style="margin-left:120px; text-align:center;">Số lượng trong kho</div>
                    </li>
                    <li>
                        <div class="body-title" style="margin-left:50px"></div>
                    </li>
                </ul>
                <ul class="flex flex-column">

                    @foreach (var item in Model)
                    {
                        <li class="product-item gap14">
                            <div class="image no-bg">
                                <img src="~/assets/images/product/@item.Product.Images" alt="">
                            </div>
                            <div class="flex items-center justify-between gap20 flex-grow">
                                <div class="name" style="min-width:500px;">
                                    <a href="@Url.Action("Details", "Product_Size", new {id=item.Product_SizeID})" class="body-title-2">@item.Product.ProductName</a>
                                </div>
                                <div class="body-text">@item.Quantity</div>
                                <div class="list-icon-function">
                                    <div class="item eye">
                                        <a href="@Url.Action("Details","Product_Size", new {id=item.Product_SizeID})"><i class="icon-eye"></i></a>
                                    </div>
                                    <div class="item edit">
                                        <a href="@Url.Action("Edit","Product_Size", new {id=item.Product_SizeID})"><i class="icon-edit-3"></i></a>
                                    </div>
                                    <div class="item trash">
                                        <a href="@Url.Action("Delete","Product_Size", new {id=item.Product_SizeID})"><i class="icon-trash-2"></i></a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    }


                </ul>
            </div>
            <div class="divider"></div>
            <div class="flex items-center justify-between flex-wrap gap10">
                <div class="text-tiny"></div>
                <ul class="wg-pagination">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, PageSize = 8 }))
                </ul>
            </div>
        </div>
        <!-- /all-attribute -->
    </div>
    <!-- /main-content-wrap -->
</div>
<div class="bottom-page">
    <div class="body-text">Copyright © 2024 Mobile</div>
    <i class="icon-heart"></i>
</div>