DoAnTotNghiep_New/DoAnTotNghiep/DoAn_NguyenVanTruong/Models/Slide.cs
namespace DoAnNguyenVanTruong.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Slide")]
    public partial class Slide
    {
        public int SlideID { get; set; }

        [StringLength(255)]
        public string Images { get; set; }
    }
}

DoAnTotNghiep_New/DoAnTotNghiep/DoAn_NguyenVanTruong/Controllers/SlidesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DoAnNguyenVanTruong.Models;
using PagedList;

namespace DoAnNguyenVanTruong.Controllers
{
    public class SlidesController : Controller
    {
        private BaseAppDbContext db = new BaseAppDbContext();

        // GET: Slides
        public ActionResult Index(int? page, int? PageSize)
        {
            if (page == null)
            {
                page = 1;
            }
            if (PageSize == null)
            {

                PageSize = 8;
            }
            var slides = db.Slides.ToList();
            return View(slides.ToPagedList((int)page, (int)PageSize));
        }
        // GET: Slides/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slide slide = db.Slides.Find(id);
            if (slide == null)
            {
                return HttpNotFound();
            }
            return View(slide);
        }

        // GET: Slides/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Slides/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SlideID,Images")] Slide slide)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string filename = System.IO.Path.GetFileName(f.FileName);
                        string Upload = Server.MapPath("~/assets/images/slide/" + f.FileName);
                        f.SaveAs(Upload);
                        slide.Images = filename;
                    }
                    db.Slides.Add(slide);
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            catch
            {

                return View(slide);
            }
        }

        // GET: Slides/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slide slide = db.Slides.Find(id);
            if (slide == null)
            {
                return HttpNotFound();
            }
            return View(slide);
        }

        // POST: Slides/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SlideID,Images")] Slide slide)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var f = Request.Files["ImageFile"];
                    if (f != null && f.ContentLength > 0)
                    {
                        string filename = System.IO.Path.GetFileName(f.FileName);
                        string Upload = Server.MapPath("~/assets/images/slide/" + f.FileName);
                        f.SaveAs(Upload);
                        slide.Images = filename;
                    }
                    db.Entry(slide).State = EntityState.Modified;
                    db.SaveChanges();
                }
                return RedirectToAction("Index");
            }

            catch
            {

                return View(slide);
            }
        }

        // GET: Slides/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Slide slide = db.Slides.Find(id);
            if (slide == null)
            {
                return HttpNotFound();
            }
            return View(slide);
        }

        // POST: Slides/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Slide slide = db.Slides.Find(id);
            db.Slides.Remove(slide);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DoAnTotNghiep_New/DoAnTotNghiep/DoAn_NguyenVanTruong/Views/Slides/Create.cshtml
@model DoAnNguyenVanTruong.Models.Slide

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}
<div class="main-content-inner">
    <!-- main-content-wrap -->
    <div class="main-content-wrap">
        <div class="flex items-center flex-wrap justify-between gap20 mb-27">
            <h3>Tạo Slide mới</h3>
            <ul class="breadcrumbs flex items-center flex-wrap justify-start gap10">
                <li>
                    <a href="@Url.Action("Dashboard","Admin")"><div class="text-tiny">Trang chủ</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <a href="@Url.Action("Index","Slides")"><div class="text-tiny">Slide</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <div class="text-tiny">Tạo mới Slide</div>
                </li>
            </ul>
        </div>
        <!-- new-category -->
        <div class="wg-box">
            <form action="/Slides/Create" method="post" enctype="multipart/form-data" class="form-new-product form-style-1">
                @Html.AntiForgeryToken()

                <fieldset>
                    <div class="body-title">Upload images <span class="tf-color-1">*</span></div>
                    <div class="upload-image flex-grow">
                        <div class="item up-load">
                            <div class="item">
                                <img id="output" src="~/assets/images/slide/" alt="" style="border-radius: 12px; border: 1px solid #ECF0F4" />
                            </div>
                            <label class="uploadfile" for="myFile">
                                <span class="icon">
                                    <i class="icon-upload-cloud"></i>
                                </span>
                                <span class="text-tiny"> <span class="tf-color">Tải file lên</span></span>
                                <input name="ImageFile" id="myFile" type="file" onchange="LoadFile(event)" />
                            </label>
                        </div>
                    </div>
                </fieldset>



                <div class="bot">
                    <div></div>
                    <button class="tf-button w208" type="submit">Thêm mới Slide</button>
                </div>
            </form>
        </div>
        <!-- /new-category -->
    </div>
    <!-- /main-content-wrap -->
</div>
<div class="bottom-page">
    <div class="body-text">Copyright © 2024 Mobile</div>
    <i class="icon-heart"></i>
</div>
<script>
    var LoadFile = function (event) {
        var image = document.getElementById("output");
        image.src = URL.createObjectURL(event.target.files[0]);
    };
</script>

DoAnTotNghiep_New/DoAnTotNghiep/DoAn_NguyenVanTruong/Views/Slides/Delete.cshtml
@model DoAnNguyenVanTruong.Models.Slide

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}
<div class="main-content-inner">
    <!-- main-content-wrap -->
    <div class="main-content-wrap">
        <div class="flex items-center flex-wrap justify-between gap20 mb-27">
            <h3>Xoá Slide</h3>
            <ul class="breadcrumbs flex items-center flex-wrap justify-start gap10">
                <li>
                    <a href="@Url.Action("Dashboard","Admin")"><div class="text-tiny">Trang chủ</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <a href="@Url.Action("Index","Slides")"><div class="text-tiny">Slide</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <div class="text-tiny">Xoá Slide</div>
                </li>
            </ul>
        </div>
        <!-- new-category -->
        <div class="wg-box">
            <form action="/Slides/Delete/@Model.SlideID" method="post" class="form-new-product form-style-1">
                @Html.AntiForgeryToken()
                <fieldset>
                    <div class="body-title">Upload images <span class="tf-color-1">*</span></div>
                    <div class="upload-image flex-grow">
                        <div class="item up-load">
                            <div class="item">
                                <img id="output" src="~/assets/images/slide/@Model.Images" alt="" style="border-radius: 12px; border: 1px solid #ECF0F4" />
                            </div>

                        </div>
                    </div>
                </fieldset>
                <div class="bot">
                    <div></div>
                    <button class="tf-button w208" type="submit">Xoá Slide</button>
                </div>
            </form>
        </div>
        <!-- /new-category -->
    </div>
    <!-- /main-content-wrap -->
</div>
<div class="bottom-page">
    <div class="body-text">Copyright © 2024 Mobile</div>
    <i class="icon-heart"></i>
</div>

DoAnTotNghiep_New/DoAnTotNghiep/DoAn_NguyenVanTruong/Views/Slides/Details.cshtml
@model DoAnNguyenVanTruong.Models.Slide

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}
<div class="main-content-inner">
    <!-- main-content-wrap -->
    <div class="main-content-wrap">
        <div class="flex items-center flex-wrap justify-between gap20 mb-27">
            <h3>Chi tiết Slide</h3>
            <ul class="breadcrumbs flex items-center flex-wrap justify-start gap10">
                <li>
                    <a href="@Url.Action("Dashboard","Admin")"><div class="text-tiny">Trang chủ</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <a href="@Url.Action("Index","Slides")"><div class="text-tiny">Slide</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <div class="text-tiny">Chi tiết Slide</div>
                </li>
            </ul>
        </div>
        <!-- new-category -->
        <div class="wg-box">
            <form class="form-new-product form-style-1">


                <fieldset>
                    <div class="body-title">Upload images <span class="tf-color-1">*</span></div>
                    <div class="upload-image flex-grow">
                        <div class="item up-load">
                            <div class="item">
                                <img id="output" src="~/assets/images/slide/@Model.Images" alt="" style="border-radius: 12px; border: 1px solid #ECF0F4" />
                            </div>

                        </div>
                    </div>
                </fieldset>
                <div class="bot">
                    <div></div>
                    <a href="/Slides/Edit/@Model.SlideID" class="tf-button w208" type="submit">Sửa Slide</a>
                </div>
            </form>
        </div>
        <!-- /new-category -->
    </div>
    <!-- /main-content-wrap -->
</div>
<div class="bottom-page">
    <div class="body-text">Copyright © 2024 Mobile</div>
    <i class="icon-heart"></i>
</div>

DoAnTotNghiep_New/DoAnTotNghiep/DoAn_NguyenVanTruong/Views/Slides/Edit.cshtml
@model DoAnNguyenVanTruong.Models.Slide

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}
<div class="main-content-inner">
    <!-- main-content-wrap -->
    <div class="main-content-wrap">
        <div class="flex items-center flex-wrap justify-between gap20 mb-27">
            <h3>Sửa Slide</h3>
            <ul class="breadcrumbs flex items-center flex-wrap justify-start gap10">
                <li>
                    <a href="@Url.Action("Dashboard","Admin")"><div class="text-tiny">Trang chủ</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <a href="@Url.Action("Index","Slides")"><div class="text-tiny">Slide</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <div class="text-tiny">Xoá Slide</div>
                </li>
            </ul>
        </div>
        <!-- new-category -->
        <div class="wg-box">
            <form action="/Slides/Edit" method="post" enctype="multipart/form-data" class="form-new-product form-style-1">
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.SlideID)

                <fieldset>
                    <div class="body-title">Upload images <span class="tf-color-1">*</span></div>
                    <div class="upload-image flex-grow">
                        <div class="item up-load">
                            <div class="item">
                                <img id="output" src="~/assets/images/slide/@Model.Images" alt="" style="border-radius: 12px; border: 1px solid #ECF0F4" />
                            </div>
                            <label class="uploadfile" for="myFile">
                                <span class="icon">
                                    <i class="icon-upload-cloud"></i>
                                </span>
                                <span class="text-tiny"> <span class="tf-color">Tải file lên</span></span>
                                <input name="ImageFile" id="myFile" type="file" onchange="LoadFile(event)" />
                            </label>
                        </div>
                    </div>
                </fieldset>



                <div class="bot">
                    <div></div>
                    <button class="tf-button w208" type="submit">Lưu Slide</button>
                </div>
            </form>
        </div>
        <!-- /new-category -->
    </div>
    <!-- /main-content-wrap -->
</div>
<div class="bottom-page">
    <div class="body-text">Copyright © 2024 Mobile</div>
    <i class="icon-heart"></i>
</div>
<script>
    var LoadFile = function (event) {
        var image = document.getElementById("output");
        image.src = URL.createObjectURL(event.target.files[0]);
    };
</script>

DoAnTotNghiep_New/DoAnTotNghiep/DoAn_NguyenVanTruong/Views/Slides/Index.cshtml
﻿﻿@using PagedList.Mvc;
@using PagedList;
@model IPagedList<DoAnNguyenVanTruong.Models.Slide>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/LayoutAdmin.cshtml";
}
<div class="main-content-inner">
    <!-- main-content-wrap -->
    <div class="main-content-wrap">
        <div class="flex items-center flex-wrap justify-between gap20 mb-27">
            <h3>Danh sách Banner</h3>
            <ul class="breadcrumbs flex items-center flex-wrap justify-start gap10">
                <li>
                    <a href="@Url.Action("Dashboard","Admin")"><div class="text-tiny">Trang chủ</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <a href="@Url.Action("Index","Slides")"><div class="text-tiny">Banner</div></a>
                </li>
                <li>
                    <i class="icon-chevron-right"></i>
                </li>
                <li>
                    <div class="text-tiny">Danh sách Banner</div>
                </li>
            </ul>
        </div>
        <!-- all-category -->
        <div class="wg-box">
            <div class="flex items-center justify-between gap10 flex-wrap">
                <div class="wg-filter flex-grow">
                    <a class="tf-button style-1 w208" href="@Url.Action("Create","Slides")"><i class="icon-plus"></i>Thêm mới</a>

                </div>

            </div>
            <div class="wg-table table-all-category">
                <ul class="table-title flex gap20 mb-14" style="min-width:151px;">
                    <li>
                        <div class="body-title">Banner</div>
                    </li>
                    <li>
                        <div class="body-title"></div>
                    </li>
                    <li>
                        <div class="body-title">Hành động</div>
                    </li>
                </ul>
                <ul class="flex flex-column" style="min-width:151px;">
                    @foreach (var item in Model)
                    {
                        <li class="product-item gap14">
                            <div class="image no-bg">
                                <img src="~/assets/images/slide/@item.Images" alt="" style="width: 50px; height: 50px">
                            </div>
                            <div class="flex items-center justify-between gap20 flex-grow">
                                <div class="name">

                                </div>
                                <div class="list-icon-function">
                                    <div class="item eye">
                                        <a href="@Url.Action("Details", "Slides", new {id=item.SlideID})">
                                            <i class="icon-eye"></i>
                                        </a>
                                    </div>
                                    <div class="item edit">
                                        <a href="@Url.Action("Edit", "Slides", new {id=item.SlideID})">
                                            <i class="icon-edit-3"></i>
                                        </a>
                                    </div>
                                    <div class="item trash">
                                        <a href="@Url.Action("Delete", "Slides", new {id=item.SlideID})">
                                            <i class="icon-trash-2"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    }


                </ul>
            </div>
            <div class="divider"></div>
            <div class="flex items-center justify-between flex-wrap gap10">
                <div class="text-tiny"></div>
                <ul class="wg-pagination">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, PageSize = 8 }))
                </ul>
            </div>
        </div>
        <!-- /all-category -->
    </div>
    <!-- /main-content-wrap -->
</div>
<div class="bottom-page">
    <div class="body-text">Copyright © 2024 Mobile</div>
    <i class="icon-heart"></i>
</div>